### ISSUE TITLE
Doesn't find bookmarks.

### ISSUE THREAD

**Issue by zepocas** [iamfitsum/arc-export-windows#1]
I have a StorableSidebar file with 300kb. The script finds nothingf

![image](https://github.com/user-attachments/assets/e2fc368b-0d7b-4212-b51f-615b0a444c61)

**Comment by iamfitsum** [comment]
The script's purpose is *not* to retrieve all bookmarks from the Arc browser. Arc already provides an easy way to export bookmarks directly. However, the **sidebar**, including pinned tabs, cannot be exported through Arc's built-in features.

This script specifically addresses that limitation. It extracts the **pinned tabs in the Arc sidebar** (stored in the `StorableSidebar.json` file), converts them into a structured bookmarks format, and exports them as an HTML file. This allows users to transfer their pinned tabs to other browsers or save them for future use.

To use the script:
1. Locate the `StorableSidebar.json` file as described in the README.
2. Place it in the script's directory.
3. Run the script, and it will generate an HTML file you can use to import the pinned tabs elsewhere.

Let me know if you need help setting it up!

**Comment by zepocas** [comment]
Just to follow up on this, I later figured out that as I was an early beta adopter (just a guess), my storableSidebar had a weird structure. I ended up manually converting it into the expected format and after that the script worked just fine 👍 thanks for the answer.

**Comment by zepocas** [comment]
> The script's purpose is _not_ to retrieve all bookmarks from the Arc browser. Arc already provides an easy way to export bookmarks directly. However, the **sidebar**, including pinned tabs, cannot be exported through Arc's built-in features.
> 
> This script specifically addresses that limitation. It extracts the **pinned tabs in the Arc sidebar** (stored in the `StorableSidebar.json` file), converts them into a structured bookmarks format, and exports them as an HTML file. This allows users to transfer their pinned tabs to other browsers or save them for future use.
> 
> To use the script:
> 
>     1. Locate the `StorableSidebar.json` file as described in the README.
> 
>     2. Place it in the script's directory.
> 
>     3. Run the script, and it will generate an HTML file you can use to import the pinned tabs elsewhere.
> 
> 
> Let me know if you need help setting it up!

Just to follow up on this, I later figured out that as I was an early beta adopter (just a guess), my storableSidebar had a weird structure. I ended up manually converting it into the expected format and after that the script worked just fine 👍 thanks for the answer.

**Comment by zepocas** [comment]
> The script's purpose is _not_ to retrieve all bookmarks from the Arc browser. Arc already provides an easy way to export bookmarks directly. However, the **sidebar**, including pinned tabs, cannot be exported through Arc's built-in features.
> 
> This script specifically addresses that limitation. It extracts the **pinned tabs in the Arc sidebar** (stored in the `StorableSidebar.json` file), converts them into a structured bookmarks format, and exports them as an HTML file. This allows users to transfer their pinned tabs to other browsers or save them for future use.
> 
> To use the script:
> 
>     1. Locate the `StorableSidebar.json` file as described in the README.
> 
>     2. Place it in the script's directory.
> 
>     3. Run the script, and it will generate an HTML file you can use to import the pinned tabs elsewhere.
> 
> 
> Let me know if you need help setting it up!

Just to follow up on this, I later figured out that as I was an early beta adopter (just a guess), my storableSidebar had a weird structure. I ended up manually converting it into the expected format and after that the script worked just fine 👍 thanks for the answer.

**Comment by iamfitsum** [comment]
Thanks for the follow-up! Glad you got it working. 😊 The script is built for the standard structure, but I appreciate you flagging this variation. Feel free to reach out if anything else comes up!
